### ISSUE TITLE
Npm version not updated ?

### ISSUE THREAD

**Issue by kaosat-dev** [NaturalNode/node-sylvester#9] opened 2017-01-16 14:20 UTC
Hi ! I am running into a small issue : apparently the version on NPM (version number matches the one here ) does not include the updated package.json with : 
```
browser": {
    "lapack": false
  }
```

which breaks  browserified builds: would it be just possible to publish a version to npm with an updated package.json , that is all that is needed to fix things :)
Thanks in advance !

**Comment by connor4312** [comment] 2017-01-16 16:43
Hi Kaosat,

The version which includes the browser flag is still a work in progress. I should have an update this coming weekend. For now I'd recommend that you use the `--ignore`` flag in Browserify.

**Comment by kaosat-dev** [comment] 2017-01-16 17:37
Hi Connor !
Thanks for the heads up !
Sadly the '--ignore' flag  for Browserify does not solve my issue since sylvester is used in a dependency of a dependency and `ignore` only works one level down :)

**Comment by kaosat-dev** [comment] 2017-01-16 18:05
there is no rush btw, I'll browserify the intermediary module in the meantime

**Comment by connor4312** [comment] 2017-01-16 18:10
Okay, sorry about that, thanks for opening an issue! Closing as a dupe of https://github.com/NaturalNode/node-sylvester/issues/4.

**Closed by connor4312** 2017-01-16 18:10 UTC
